# ==============================================================================
# Monte Carlo Simulation Study for xtife
# Target: JSS submission — replication script for Tables 1–6
#
# Model:  y_it = x_it' beta + lambda_i' F_t + u_it
# Truth:  beta_true = 1.0,  r_true = 2
#
# Four DGPs:
#   1. Static balanced   — ife()          + Bai (2009) bias correction
#   2. Static unbalanced — ife_unbalanced() + SWW2025 bias correction
#   3. Dynamic balanced  — ife(method="dynamic") + Moon & Weidner (2017) BC
#   4. Dynamic unbalanced— ife_unbalanced(exog="weak", se="hac") + SWW2025 BC
#
# Each DGP × r known / r unknown (two-step: select r, then estimate)
# Section 6: OLS init vs NNR init comparison for severely unbalanced panels
#
# Author: generated by Claude; reviewed by user
# Date  : 2026-04-30
# ==============================================================================


# ==============================================================================
# SECTION 0 — Setup, parameters, parallel configuration
# ==============================================================================

library(xtife)

## ---- Reproducibility --------------------------------------------------------
RNGkind("L'Ecuyer-CMRG")
set.seed(2025L)

## ---- Parallel ---------------------------------------------------------------
nc <- max(1L, parallel::detectCores() - 1L)
cat(sprintf("Using %d cores for parallel simulation.\n", nc))

## ---- Grid -------------------------------------------------------------------
B         <- 1000L          # replications per cell (MC-SE for coverage ≈ 0.007)
N_grid    <- c(30L, 50L, 100L, 200L)
T_grid    <- c(10L, 50L, 100L, 200L)
r_true    <- 2L             # true number of factors
r_max     <- 5L             # upper bound for factor selection
beta_true <- 1.0            # true structural coefficient
fill_rate <- 0.8            # fraction of cells observed (unbalanced DGPs)

## ---- DGP-level seeds (deterministic, cross-session reproducible) ------------
# seed for replication b in DGP d, grid cell g:
#   dgp_id * 1e6  +  g * 1e3  +  b
# Avoids seed collisions across DGPs and cells.


# ==============================================================================
# SECTION 1 — DGP Generator Functions
# ==============================================================================

# ------------------------------------------------------------------------------
# DGP 1: Static balanced panel
#   y_it = beta * x_it + lambda_i' F_t + u_it
#   x_it = gamma * (lambda_i' F_t) + eps_it    [eps ~ N(0,1)]
#   Endogeneity: x correlated with factors -> TWFE is biased; IFE corrects it.
#   Incidental-parameter bias of IFE: O(1/N + 1/T) -> Bai (2009) BC needed.
# ------------------------------------------------------------------------------
dgp_static_balanced <- function(N, TT, r, beta,
                                 gamma    = 1.0,
                                 sigma_u  = 1.0,
                                 seed     = NULL) {
  if (!is.null(seed)) set.seed(seed)

  F_true      <- matrix(rnorm(TT * r), TT, r)
  Lambda_true <- matrix(rnorm(N  * r), N,  r)

  # factor component: NT-vector (expand.grid varies unit (i) first, so
  # the (i,t) ordering matches as.vector(F_true %*% t(Lambda_true)) — see below)
  df <- expand.grid(unit = seq_len(N), time = seq_len(TT))
  # expand.grid: unit is inner (fast) loop, time is outer (slow) loop
  # F_true %*% t(Lambda_true) is TT x N; as.vector() stacks columns (N blocks of TT)
  # To get NT rows ordered (unit,time) we need: Lambda_true %*% t(F_true) then t() then as.vector()
  # Simpler: use the fact that expand.grid order is unit=1..N for each t
  factor_mat <- Lambda_true %*% t(F_true)   # N x TT
  # Row i, col t = lambda_i' F_t; expand.grid row index = (t-1)*N + i
  fc <- as.vector(t(factor_mat))            # TT*N vector in (unit,time) expand.grid order
  # Wait — expand.grid(unit, time): first column varies first.
  # Row k: unit = ((k-1) %% N) + 1, time = ((k-1) %/% N) + 1
  # so fc[k] = lambda_{unit_k}' F_{time_k} = factor_mat[unit_k, time_k]
  # as.vector(factor_mat) stacks columns: col 1 = F_t=1, so row-wise in (unit,time) order
  # factor_mat is N x TT, as.vector gives col 1 (t=1, units 1..N), col 2 (t=2, units 1..N)...
  # expand.grid(unit,time): rows 1..N have time=1, rows N+1..2N have time=2, etc.
  # So as.vector(factor_mat) matches expand.grid order exactly.
  fc <- as.vector(factor_mat)               # N*TT vector, (unit-fast, time-slow) order

  df$X <- gamma * fc + rnorm(N * TT)
  df$Y <- beta  * df$X + fc + rnorm(N * TT, sd = sigma_u)
  df
}


# ------------------------------------------------------------------------------
# DGP 2: Static unbalanced panel (MCAR dropout from DGP 1)
# ------------------------------------------------------------------------------
dgp_static_unbalanced <- function(N, TT, r, beta,
                                   gamma   = 1.0,
                                   sigma_u = 1.0,
                                   fill    = 0.8,
                                   seed    = NULL) {
  if (!is.null(seed)) set.seed(seed)

  df_full <- dgp_static_balanced(N, TT, r, beta, gamma, sigma_u, seed = NULL)
  keep    <- sort(sample(nrow(df_full), floor(fill * nrow(df_full))))
  df_full[keep, ]
}


# ------------------------------------------------------------------------------
# DGP 3: Dynamic balanced panel (Moon & Weidner 2017 DGP)
#   y_it = beta * y_{i,t-1} + lambda_i' F_t + u_it
#   F_t  = rho_f * F_{t-1} + eta_t,  eta ~ N(0, 1-rho_f^2)  [stationary AR(1)]
#   u_it = (e_it + theta_ma * e_{i,t-1}) / sqrt(1 + theta_ma^2)  [MA(1), unit var]
#   T0_burnin periods discarded to remove initial-condition effects.
# ------------------------------------------------------------------------------
dgp_dynamic_balanced <- function(N, TT, r, beta,
                                  rho_f     = 0.5,
                                  theta_ma  = 0.5,
                                  sigma_u   = 1.0,
                                  T0_burnin = 50L,
                                  seed      = NULL) {
  if (!is.null(seed)) set.seed(seed)

  TT_total <- TT + T0_burnin

  # AR(1) factors (stationary, variance = 1)
  sv_eta <- sqrt(1 - rho_f^2)
  F_mat  <- matrix(0, TT_total, r)
  F_mat[1L, ] <- rnorm(r)
  for (tt in 2L:TT_total)
    F_mat[tt, ] <- rho_f * F_mat[tt - 1L, ] + rnorm(r, sd = sv_eta)

  Lambda_true <- matrix(rnorm(N * r), N, r)

  # MA(1) errors (unit variance)
  e_mat <- matrix(rnorm(TT_total * N), TT_total, N)
  sv_ma <- sqrt(1 + theta_ma^2)
  u_mat <- (e_mat +
             theta_ma * rbind(matrix(0, 1L, N), e_mat[-TT_total, ])) / sv_ma

  # Build Y (dynamic AR in outcome)
  Y_mat <- matrix(0, TT_total, N)
  Y_mat[1L, ] <- as.vector(F_mat[1L, , drop = FALSE] %*% t(Lambda_true)) +
                 sigma_u * u_mat[1L, ]
  for (tt in 2L:TT_total) {
    ft <- as.vector(F_mat[tt, , drop = FALSE] %*% t(Lambda_true))   # N-vector
    Y_mat[tt, ] <- beta * Y_mat[tt - 1L, ] + ft + sigma_u * u_mat[tt, ]
  }

  # Drop burn-in; effective periods after lagging: TT - 1
  idx_y  <- (T0_burnin + 2L):TT_total          # outcome rows
  idx_x  <- (T0_burnin + 1L):(TT_total - 1L)   # lagged Y (= regressor)
  n_t    <- length(idx_y)                       # = TT - 1

  Y_use  <- Y_mat[idx_y, ]   # n_t x N
  X_use  <- Y_mat[idx_x, ]   # n_t x N  (lagged outcome)

  df <- data.frame(
    unit = rep(seq_len(N),  each  = n_t),
    time = rep(seq_len(n_t), times = N),
    Y    = as.vector(Y_use),
    X    = as.vector(X_use)
  )
  list(df = df, TT_eff = n_t)
}


# ------------------------------------------------------------------------------
# DGP 4: Dynamic unbalanced panel (MCAR dropout from DGP 3)
# ------------------------------------------------------------------------------
dgp_dynamic_unbalanced <- function(N, TT, r, beta,
                                    fill = 0.8,
                                    ...,
                                    seed = NULL) {
  res     <- dgp_dynamic_balanced(N, TT, r, beta, ..., seed = seed)
  df_full <- res$df
  keep    <- sort(sample(nrow(df_full), floor(fill * nrow(df_full))))
  list(df = df_full[keep, ], TT_eff = res$TT_eff)
}


# ==============================================================================
# SECTION 2 — One-Rep Estimation Function
# Returns a named numeric vector with all per-replication statistics.
# ==============================================================================

run_one_rep <- function(N, TT, r_true, r_max, dgp_id,
                        beta_true, fill = 0.8,
                        seed = NULL) {

  # ---- Generate data ----
  df <- switch(as.character(dgp_id),
    "1" = dgp_static_balanced(N, TT, r_true, beta_true, seed = seed),
    "2" = dgp_static_unbalanced(N, TT, r_true, beta_true,
                                 fill = fill, seed = seed),
    "3" = dgp_dynamic_balanced(N, TT, r_true, beta_true, seed = seed)$df,
    "4" = dgp_dynamic_unbalanced(N, TT, r_true, beta_true,
                                  fill = fill, seed = seed)$df
  )

  idx  <- c("unit", "time")
  out  <- rep(NA_real_, 21L)
  names(out) <- c(
    "b_ols",                                          # OLS (no factors)
    "b_kn", "b_bc",                                   # IFE r-known: raw, bias-corrected
    "se_kn_std", "se_kn_rob", "se_kn_cl",            # SE of b_kn
    "cov_kn_std", "cov_kn_rob", "cov_kn_cl",         # 95% CI coverage (r known)
    "cov_bc_std",                                     # coverage of BC estimator (std SE)
    "size_kn_std",                                    # size: |t_std| > 1.96 under H0
    "r_hat", "r_correct",                             # factor selection (r unknown)
    "b_un",                                           # IFE r-unknown (BC after selection)
    "cov_un_std",                                     # coverage of b_un (std SE)
    "conv",                                           # convergence: 1 = yes
    "n_iter",                                         # outer iterations
    "b_hac",                                          # SE type hac (DGP 3/4 only)
    "cov_kn_hac",                                     # coverage with HAC SE
    "se_kn_hac",                                      # HAC SE magnitude
    "conv_sel"                                        # factor selection converged
  )

  tryCatch({

    # ---- (A) OLS baseline (r=0, no factors) ----
    # ife() requires a balanced panel; use lm() for unbalanced DGPs 2 and 4.
    out["b_ols"] <- if (dgp_id %in% c(1L, 3L)) {
      fit_ols <- ife(Y ~ X, data = df, index = idx,
                    r = 0L, force = "none", se = "standard")
      unname(fit_ols$coef["X"])
    } else {
      # DGPs 2 & 4: plain OLS via lm() on observed (unbalanced) data
      unname(coef(lm(Y ~ X, data = df))["X"])
    }

    # ---- (B) IFE r known ----
    if (dgp_id == 1L) {
      # Static balanced — Bai (2009) static BC
      fit_std <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "standard", bias_corr = FALSE)
      fit_bc  <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "standard", bias_corr = TRUE)
      fit_rob <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "robust",   bias_corr = FALSE)
      fit_cl  <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "cluster",  bias_corr = FALSE)

    } else if (dgp_id == 2L) {
      # Static unbalanced — SWW2025 strict-exog BC
      # suppressWarnings: EM inner-loop may warn on early iterations for
      # small panels; this does not affect correctness (outer loop continues).
      fit_std <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "standard", bias_corr = FALSE))
      fit_bc  <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "standard", bias_corr = TRUE,
                       exog = "strict"))
      fit_rob <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "robust",   bias_corr = FALSE))
      fit_cl  <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "cluster",  bias_corr = FALSE))

    } else if (dgp_id == 3L) {
      # Dynamic balanced — Moon & Weidner (2017) dynamic BC
      fit_std <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "standard", method = "dynamic",
                     bias_corr = FALSE)
      fit_bc  <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "standard", method = "dynamic",
                     bias_corr = TRUE, M1 = 1L)
      fit_rob <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "robust",   method = "dynamic",
                     bias_corr = FALSE)
      fit_cl  <- ife(Y ~ X, data = df, index = idx, r = r_true,
                     force = "none", se = "cluster",  method = "dynamic",
                     bias_corr = FALSE)

    } else {
      # dgp_id == 4L: Dynamic unbalanced — SWW2025 weak-exog + HAC
      fit_std <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "standard", bias_corr = FALSE,
                       exog = "strict"))
      fit_bc  <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "hac", bias_corr = TRUE,
                       exog = "weak"))
      fit_rob <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "robust",   bias_corr = FALSE,
                       exog = "strict"))
      fit_cl  <- suppressWarnings(
        ife_unbalanced(Y ~ X, data = df, index = idx,
                       r = r_true, se = "cluster",  bias_corr = FALSE,
                       exog = "strict"))
    }

    # Extract b, SE, CI
    b_kn  <- unname(fit_std$coef["X"])
    b_bc  <- unname(fit_bc$coef["X"])
    se_std <- unname(fit_std$se["X"])
    se_rob <- unname(fit_rob$se["X"])
    se_cl  <- unname(fit_cl$se["X"])

    ci_std <- fit_std$ci["X", ]
    ci_rob <- fit_rob$ci["X", ]
    ci_cl  <- fit_cl$ci["X",  ]
    ci_bc  <- fit_bc$ci["X",  ]

    # Convergence
    conv   <- as.integer(fit_std$converged)
    n_iter <- if (!is.null(fit_std$n_iter)) fit_std$n_iter else NA_integer_

    # HAC SE (for DGP 4 — already in fit_bc; also compute standalone for DGP 3)
    se_hac   <- NA_real_
    ci_hac_l <- NA_real_; ci_hac_h <- NA_real_
    if (dgp_id == 3L) {
      # For DGP 3 (balanced dynamic), no native HAC in ife(); use cluster as proxy
      se_hac   <- se_cl
      ci_hac_l <- ci_cl[1L]; ci_hac_h <- ci_cl[2L]
    } else if (dgp_id == 4L) {
      se_hac   <- unname(fit_bc$se["X"])
      ci_hac_l <- ci_bc[1L]; ci_hac_h <- ci_bc[2L]
    }

    out["b_kn"]      <- b_kn
    out["b_bc"]      <- b_bc
    out["se_kn_std"] <- se_std
    out["se_kn_rob"] <- se_rob
    out["se_kn_cl"]  <- se_cl
    out["se_kn_hac"] <- se_hac
    out["b_hac"]     <- if (dgp_id == 4L) b_bc else b_kn

    # 95% coverage (1 = covered, 0 = not)
    out["cov_kn_std"] <- as.integer(ci_std[1L] <= beta_true & beta_true <= ci_std[2L])
    out["cov_kn_rob"] <- as.integer(ci_rob[1L] <= beta_true & beta_true <= ci_rob[2L])
    out["cov_kn_cl"]  <- as.integer(ci_cl[1L]  <= beta_true & beta_true <= ci_cl[2L])
    out["cov_bc_std"] <- as.integer(ci_bc[1L]  <= beta_true & beta_true <= ci_bc[2L])
    out["cov_kn_hac"] <- if (!is.na(ci_hac_l))
                           as.integer(ci_hac_l <= beta_true & beta_true <= ci_hac_h)
                         else NA_real_

    # Size test (H0: beta = beta_true): reject if |t| > 1.96 (should be ~5%)
    out["size_kn_std"] <- as.integer(abs((b_kn - beta_true) / se_std) > 1.96)
    out["conv"]   <- conv
    out["n_iter"] <- n_iter

    # ---- (C) Factor selection (r unknown) ----
    r_hat <- tryCatch({
      if (dgp_id <= 2L) {
        sel <- suppressWarnings(
          if (dgp_id == 1L)
            ife_select_r(Y ~ X, data = df, index = idx,
                         r_max = r_max, force = "none", verbose = FALSE)
          else
            ife_select_r_unb(Y ~ X, data = df, index = idx, verbose = FALSE)
        )
        if (dgp_id == 1L) {
          as.integer(attr(sel, "suggested")["IC_bic"])
        } else {
          as.integer(sel$r_hat)
        }
      } else {
        # Dynamic — use same static selection (factor count is the same)
        sel <- suppressWarnings(
          if (dgp_id == 3L)
            ife_select_r(Y ~ X, data = df, index = idx,
                         r_max = r_max, force = "none", verbose = FALSE)
          else
            ife_select_r_unb(Y ~ X, data = df, index = idx, verbose = FALSE)
        )
        if (dgp_id == 3L)
          as.integer(attr(sel, "suggested")["IC_bic"])
        else
          as.integer(sel$r_hat)
      }
    }, error = function(e) NA_integer_)

    out["conv_sel"] <- as.integer(!is.na(r_hat))
    r_hat           <- if (is.na(r_hat)) r_true else max(1L, min(r_hat, r_max))
    out["r_hat"]    <- r_hat
    out["r_correct"] <- as.integer(r_hat == r_true)

    # ---- (D) IFE r unknown (two-step: select r, then estimate with BC) ----
    fit_un <- tryCatch({
      suppressWarnings(
        if (dgp_id == 1L) {
          ife(Y ~ X, data = df, index = idx, r = r_hat,
              force = "none", se = "standard", bias_corr = TRUE)
        } else if (dgp_id == 2L) {
          ife_unbalanced(Y ~ X, data = df, index = idx, r = r_hat,
                         se = "standard", bias_corr = TRUE, exog = "strict")
        } else if (dgp_id == 3L) {
          ife(Y ~ X, data = df, index = idx, r = r_hat,
              force = "none", se = "standard", method = "dynamic",
              bias_corr = TRUE, M1 = 1L)
        } else {
          ife_unbalanced(Y ~ X, data = df, index = idx, r = r_hat,
                         se = "hac", bias_corr = TRUE, exog = "weak")
        }
      )
    }, error = function(e) NULL)

    if (!is.null(fit_un)) {
      b_un    <- unname(fit_un$coef["X"])
      ci_un   <- fit_un$ci["X", ]
      out["b_un"]      <- b_un
      out["cov_un_std"] <- as.integer(ci_un[1L] <= beta_true & beta_true <= ci_un[2L])
    }

  }, error = function(e) {
    # All entries remain NA on error; conv stays NA too
    invisible(NULL)
  })

  out
}


# ==============================================================================
# SECTION 3 — Summary Statistics
# ==============================================================================

summarise_reps <- function(mat, beta_true) {
  B     <- nrow(mat)
  b_ols <- mat[, "b_ols"]
  b_kn  <- mat[, "b_kn"]
  b_bc  <- mat[, "b_bc"]
  b_un  <- mat[, "b_un"]
  se_std <- mat[, "se_kn_std"]
  r_hat  <- mat[, "r_hat"]

  cov_mean <- function(x) mean(x, na.rm = TRUE)
  cov_se   <- function(x) {
    m <- cov_mean(x)
    sqrt(m * (1 - m) / max(1L, sum(!is.na(x))))
  }

  data.frame(
    # --- OLS baseline ---
    OLS.Bias      = mean(b_ols - beta_true, na.rm = TRUE),
    # --- IFE (no BC, r known) ---
    IFE.Bias      = mean(b_kn  - beta_true, na.rm = TRUE),
    IFE.SD        = sd(b_kn,   na.rm = TRUE),
    IFE.RMSE      = sqrt(mean((b_kn - beta_true)^2, na.rm = TRUE)),
    IFE.SE_SD     = mean(se_std, na.rm = TRUE) / sd(b_kn, na.rm = TRUE),
    IFE.Cov.Std   = cov_mean(mat[, "cov_kn_std"]),
    IFE.Cov.Rob   = cov_mean(mat[, "cov_kn_rob"]),
    IFE.Cov.Cl    = cov_mean(mat[, "cov_kn_cl"]),
    IFE.Cov.HAC   = cov_mean(mat[, "cov_kn_hac"]),
    IFE.Cov.SE    = cov_se(mat[, "cov_kn_std"]),
    IFE.Size      = mean(mat[, "size_kn_std"], na.rm = TRUE),
    # --- IFE + BC (r known) ---
    BC.Bias       = mean(b_bc - beta_true, na.rm = TRUE),
    BC.SD         = sd(b_bc,  na.rm = TRUE),
    BC.RMSE       = sqrt(mean((b_bc - beta_true)^2, na.rm = TRUE)),
    BC.Cov.Std    = cov_mean(mat[, "cov_bc_std"]),
    BC.Cov.SE     = cov_se(mat[, "cov_bc_std"]),
    # --- Factor selection (r unknown) ---
    r.mean        = mean(r_hat,               na.rm = TRUE),
    r.correct     = mean(mat[, "r_correct"],  na.rm = TRUE),
    r.under       = mean(r_hat < 2L,          na.rm = TRUE),
    r.over        = mean(r_hat > 2L,          na.rm = TRUE),
    # --- r unknown (two-step) ---
    UN.Bias       = mean(b_un - beta_true, na.rm = TRUE),
    UN.SD         = sd(b_un,  na.rm = TRUE),
    UN.RMSE       = sqrt(mean((b_un - beta_true)^2, na.rm = TRUE)),
    UN.Cov.Std    = cov_mean(mat[, "cov_un_std"]),
    # --- Convergence ---
    conv.rate     = mean(mat[, "conv"],   na.rm = TRUE),
    n.iter.med    = median(mat[, "n_iter"], na.rm = TRUE),
    stringsAsFactors = FALSE
  )
}


# ==============================================================================
# SECTION 4 — Main Simulation Loop
# ==============================================================================

run_dgp <- function(dgp_id, N_grid, T_grid, r_true, r_max,
                    beta_true, B, nc, fill = 0.8) {

  results_list <- list()

  # For dynamic DGPs, skip T = 10 (insufficient burn-in)
  if (dgp_id >= 3L) T_grid <- T_grid[T_grid >= 50L]

  grid <- expand.grid(N = N_grid, TT = T_grid, stringsAsFactors = FALSE)

  # Force single-threaded BLAS inside forked workers.
  # Multi-threaded BLAS (OpenBLAS, MKL) is not fork-safe on macOS/Linux:
  # after fork(), only the calling thread survives in the child, but BLAS
  # thread-pool state is copied, causing deadlocks or segfaults in eigen().
  # Setting these env-vars to "1" before mclapply disables BLAS parallelism
  # in every child process.  Performance impact is negligible because each
  # replications is itself single-threaded; parallelism comes from mclapply.
  Sys.setenv(OPENBLAS_NUM_THREADS   = "1",
             OMP_NUM_THREADS        = "1",
             MKL_NUM_THREADS        = "1",
             VECLIB_MAXIMUM_THREADS = "1")

  for (g in seq_len(nrow(grid))) {
    N  <- grid$N[g]
    TT <- grid$TT[g]
    cell_label <- paste0("N", N, "_T", TT)

    cat(sprintf("[DGP %d]  N = %3d  T = %3d  ...", dgp_id, N, TT))
    t0 <- proc.time()["elapsed"]

    # Deterministic seeds (cross-machine reproducible)
    seeds <- (dgp_id * 1000000L + g * 1000L) + seq_len(B)

    reps <- tryCatch(
      parallel::mclapply(
        seq_len(B),
        function(b) run_one_rep(N, TT, r_true, r_max, dgp_id,
                                beta_true, fill, seed = seeds[b]),
        mc.cores    = nc,
        mc.set.seed = FALSE    # seeds controlled per-replication above
      ),
      error = function(e) {
        cat(sprintf("\n  [WARNING] mclapply crashed for N=%d T=%d: %s\n",
                    N, TT, conditionMessage(e)))
        cat("  Falling back to sequential lapply ...\n")
        lapply(seq_len(B),
               function(b) run_one_rep(N, TT, r_true, r_max, dgp_id,
                                       beta_true, fill, seed = seeds[b]))
      }
    )

    # mclapply can return 'try-error' elements for crashed workers;
    # replace them with NA vectors so rbind() doesn't fail.
    n_out <- 21L
    out_names <- c(
      "b_ols","b_kn","b_bc","se_kn_std","se_kn_rob","se_kn_cl",
      "cov_kn_std","cov_kn_rob","cov_kn_cl","cov_bc_std","size_kn_std",
      "r_hat","r_correct","b_un","cov_un_std","conv","n_iter",
      "b_hac","cov_kn_hac","se_kn_hac","conv_sel"
    )
    reps <- lapply(reps, function(x) {
      if (inherits(x, "try-error") || is.null(x) || length(x) != n_out) {
        v <- rep(NA_real_, n_out); names(v) <- out_names; v
      } else x
    })

    mat  <- do.call(rbind, reps)
    summ <- summarise_reps(mat, beta_true)
    summ$N  <- N
    summ$TT <- TT

    elapsed <- proc.time()["elapsed"] - t0
    n_conv  <- sum(mat[, "conv"] == 1L, na.rm = TRUE)
    cat(sprintf("  done (%.1f s, %.0f ms/rep, %d/%d converged)\n",
                elapsed, 1000 * elapsed / B, n_conv, B))

    results_list[[cell_label]] <- summ
  }

  result_df <- do.call(rbind, results_list)
  rownames(result_df) <- names(results_list)
  result_df
}


# ---- Execute (wall time ≈ 30–120 min on 8 cores, B = 1000) ------------------
# For a quick smoke test use B = 10 and small grids; see Section at end of file.

cat("\n========== DGP 1: Static Balanced ==========\n")
res_dgp1 <- run_dgp(1L, N_grid, T_grid, r_true, r_max, beta_true, B, nc)

cat("\n========== DGP 2: Static Unbalanced (fill = 0.8) ==========\n")
res_dgp2 <- run_dgp(2L, N_grid, T_grid, r_true, r_max, beta_true, B, nc,
                    fill = fill_rate)

cat("\n========== DGP 3: Dynamic Balanced ==========\n")
res_dgp3 <- run_dgp(3L, N_grid, T_grid, r_true, r_max, beta_true, B, nc)

cat("\n========== DGP 4: Dynamic Unbalanced (fill = 0.8) ==========\n")
res_dgp4 <- run_dgp(4L, N_grid, T_grid, r_true, r_max, beta_true, B, nc,
                    fill = fill_rate)

# Save intermediate results
save(res_dgp1, res_dgp2, res_dgp3, res_dgp4,
     file = "data-raw/mc_results.RData")
cat("\nResults saved to data-raw/mc_results.RData\n")


# ==============================================================================
# SECTION 5 — Results Tables
# ==============================================================================

# Helper: round to d digits, format as fixed-point string
fmt <- function(x, d = 3L) formatC(x, digits = d, format = "f")

# --------------------------------------------------------------------------
# Format one DGP result data.frame into a publication table
# Columns: N, T, OLS_Bias, IFE_Bias, BC_Bias, IFE_SD, BC_RMSE,
#          Cov_Std, Cov_Rob, Cov_Cl, Size, r_correct, conv
# --------------------------------------------------------------------------
make_table <- function(res, label = "DGP") {
  tab <- data.frame(
    N          = res$N,
    T          = res$TT,
    OLS.Bias   = fmt(res$OLS.Bias),
    IFE.Bias   = fmt(res$IFE.Bias),
    BC.Bias    = fmt(res$BC.Bias),
    IFE.SD     = fmt(res$IFE.SD),
    BC.RMSE    = fmt(res$BC.RMSE),
    SE.SD      = fmt(res$IFE.SE_SD, 3L),
    Cov.Std    = fmt(res$IFE.Cov.Std, 3L),
    Cov.Rob    = fmt(res$IFE.Cov.Rob, 3L),
    Cov.Cl     = fmt(res$IFE.Cov.Cl,  3L),
    BC.Cov     = fmt(res$BC.Cov.Std,  3L),
    Size       = fmt(res$IFE.Size,    3L),
    r.correct  = fmt(res$r.correct,   3L),
    conv       = fmt(res$conv.rate,   3L),
    stringsAsFactors = FALSE
  )
  cat(sprintf("\n===== %s =====\n", label))
  print(tab, row.names = FALSE)
  invisible(tab)
}

tab1 <- make_table(res_dgp1, "Table 1: Static Balanced (DGP 1)")
tab2 <- make_table(res_dgp2, "Table 2: Static Unbalanced 80% (DGP 2)")
tab3 <- make_table(res_dgp3, "Table 3: Dynamic Balanced (DGP 3)")
tab4 <- make_table(res_dgp4, "Table 4: Dynamic Unbalanced 80% (DGP 4)")

# ---- Table 5: Factor selection accuracy across all DGPs ----
cat("\n===== Table 5: Factor Selection Accuracy =====\n")
tab5 <- data.frame(
  DGP       = rep(1:4, each = nrow(res_dgp1)),
  N         = c(res_dgp1$N, res_dgp2$N, res_dgp3$N, res_dgp4$N),
  T         = c(res_dgp1$TT, res_dgp2$TT, res_dgp3$TT, res_dgp4$TT),
  r.mean    = fmt(c(res_dgp1$r.mean, res_dgp2$r.mean,
                    res_dgp3$r.mean, res_dgp4$r.mean)),
  r.correct = fmt(c(res_dgp1$r.correct, res_dgp2$r.correct,
                    res_dgp3$r.correct, res_dgp4$r.correct)),
  r.under   = fmt(c(res_dgp1$r.under, res_dgp2$r.under,
                    res_dgp3$r.under, res_dgp4$r.under)),
  r.over    = fmt(c(res_dgp1$r.over, res_dgp2$r.over,
                    res_dgp3$r.over, res_dgp4$r.over)),
  stringsAsFactors = FALSE
)
print(tab5, row.names = FALSE)

# ---- Table 6: DGP 4 — HAC vs standard SE coverage ----
cat("\n===== Table 6: DGP 4 — HAC vs Standard SE Coverage =====\n")
tab6 <- data.frame(
  N         = res_dgp4$N,
  T         = res_dgp4$TT,
  Cov.Std   = fmt(res_dgp4$IFE.Cov.Std, 3L),   # standard SE (under-covers with serial corr)
  Cov.HAC   = fmt(res_dgp4$IFE.Cov.HAC, 3L),   # HAC SE (should be ≈0.95)
  BC.Cov    = fmt(res_dgp4$BC.Cov.Std,  3L),
  stringsAsFactors = FALSE
)
print(tab6, row.names = FALSE)

# ---- Optional: robustness at fill = 0.6 ----
cat("\n========== DGP 2 Robustness: fill = 0.6 ==========\n")
res_dgp2_60 <- run_dgp(2L, N_grid, T_grid, r_true, r_max, beta_true,
                        B, nc, fill = 0.6)
tab2b <- make_table(res_dgp2_60, "Table 2b: Static Unbalanced 60% (DGP 2)")


# ==============================================================================
# SECTION 6 — OLS vs NNR Initialization Comparison
# ==============================================================================
#
# DGP designed so OLS init is demonstrably inferior:
#   fill = 0.5  (50% missing — extreme unbalancedness)
#   r_true = 3  (richer factor structure)
#   SNR = var(lambda'f) / var(u) = 10  (strong signal: lambda_sd = sqrt(3))
#   N = 50, T = 50
#
# Why NNR wins: OLS ignores factors completely; with 50% fill and strong factors
# beta_hat_OLS is far from truth, requiring many outer iterations.
# NNR starts at the low-rank imputed solution, already near the fixed point.
# --------------------------------------------------------------------------

run_ols_vs_nnr <- function(N, TT, r, beta, B, nc,
                            fill           = 0.5,
                            snr_lambda_sd  = sqrt(3),   # sd of lambda_i
                            seed0          = 42L) {

  results <- parallel::mclapply(seq_len(B), function(b) {
    set.seed(seed0 + b)

    # High-SNR DGP (factors very strong)
    F_true <- matrix(rnorm(TT * r), TT, r)
    Lam    <- matrix(rnorm(N * r) * snr_lambda_sd, N, r)
    # factor component in (unit,time) expand.grid order
    fc     <- as.vector(Lam %*% t(F_true))    # N x TT -> as.vector = column-wise

    df_full <- expand.grid(unit = seq_len(N), time = seq_len(TT))
    df_full$X <- rnorm(N * TT) + fc * 0.5    # X correlated with factors
    df_full$Y <- beta * df_full$X + fc + rnorm(N * TT, sd = 0.5)

    keep <- sort(sample(nrow(df_full), floor(fill * nrow(df_full))))
    df   <- df_full[keep, ]
    idx  <- c("unit", "time")

    tryCatch({
      f_ols <- ife_unbalanced(Y ~ X, data = df, index = idx,
                              r = r, init = "ols")
      f_nnr <- ife_unbalanced(Y ~ X, data = df, index = idx,
                              r = r, init = "nnr")
      c(b_ols    = unname(f_ols$coef["X"]),
        b_nnr    = unname(f_nnr$coef["X"]),
        iter_ols = f_ols$n_iter,
        iter_nnr = f_nnr$n_iter,
        conv_ols = as.integer(f_ols$converged),
        conv_nnr = as.integer(f_nnr$converged),
        diff     = abs(f_ols$coef["X"] - f_nnr$coef["X"]))
    }, error = function(e) rep(NA_real_, 7L))

  }, mc.cores = nc, mc.set.seed = FALSE)

  mat <- do.call(rbind, results)
  colnames(mat) <- c("b_ols", "b_nnr", "iter_ols", "iter_nnr",
                     "conv_ols", "conv_nnr", "diff")
  mat
}

cat("\n========== Section 6: OLS vs NNR Init (N=50, T=50, fill=0.5, r=3) ==========\n")
mat_nnr <- run_ols_vs_nnr(N = 50L, TT = 50L, r = 3L, beta = beta_true,
                           B = B, nc = nc)

tab_nnr <- data.frame(
  Metric        = c("Bias", "RMSE", "Conv. rate (%)",
                    "Median iterations", "Mean |b_OLS - b_NNR|"),
  OLS.init      = c(
    fmt(mean(mat_nnr[, "b_ols"] - beta_true, na.rm = TRUE)),
    fmt(sqrt(mean((mat_nnr[, "b_ols"] - beta_true)^2, na.rm = TRUE))),
    fmt(100 * mean(mat_nnr[, "conv_ols"], na.rm = TRUE), 1L),
    fmt(median(mat_nnr[, "iter_ols"], na.rm = TRUE), 0L),
    fmt(mean(mat_nnr[, "diff"], na.rm = TRUE), 6L)
  ),
  NNR.init      = c(
    fmt(mean(mat_nnr[, "b_nnr"] - beta_true, na.rm = TRUE)),
    fmt(sqrt(mean((mat_nnr[, "b_nnr"] - beta_true)^2, na.rm = TRUE))),
    fmt(100 * mean(mat_nnr[, "conv_nnr"], na.rm = TRUE), 1L),
    fmt(median(mat_nnr[, "iter_nnr"], na.rm = TRUE), 0L),
    "-"
  ),
  stringsAsFactors = FALSE
)
cat("\n===== Table 6b: OLS vs NNR Initialization =====\n")
print(tab_nnr, row.names = FALSE)


# ==============================================================================
# Save all tables
# ==============================================================================

save(tab1, tab2, tab2b, tab3, tab4, tab5, tab6, tab_nnr, mat_nnr,
     file = "data-raw/mc_tables.RData")
cat("\nAll tables saved to data-raw/mc_tables.RData\n")


# ==============================================================================
# SMOKE TEST — Run before committing to full B = 1000 run
# Verify no errors on smallest grid; takes < 30 seconds.
# ==============================================================================
if (FALSE) {
  cat("\n--- Smoke test (B=5, N=30, T=10, DGP 1) ---\n")
  test_run <- run_dgp(1L, N_grid = 30L, T_grid = 10L,
                      r_true = 2L, r_max = 3L, beta_true = 1.0,
                      B = 5L, nc = 1L)
  cat("\nDGP 1 smoke test summary:\n")
  print(test_run[, c("N", "TT", "IFE.Bias", "IFE.Cov.Std", "conv.rate")])

  cat("\n--- Smoke test (B=5, N=30, T=50, DGP 2 fill=0.8) ---\n")
  test_run2 <- run_dgp(2L, N_grid = 30L, T_grid = 50L,
                       r_true = 2L, r_max = 3L, beta_true = 1.0,
                       B = 5L, nc = 1L, fill = 0.8)
  print(test_run2[, c("N", "TT", "IFE.Bias", "IFE.Cov.Std", "conv.rate")])

  cat("\n--- Smoke test (B=5, N=30, T=50, DGP 3) ---\n")
  test_run3 <- run_dgp(3L, N_grid = 30L, T_grid = 50L,
                       r_true = 2L, r_max = 3L, beta_true = 1.0,
                       B = 5L, nc = 1L)
  print(test_run3[, c("N", "TT", "IFE.Bias", "BC.Cov.Std", "conv.rate")])

  cat("\n--- OLS vs NNR smoke test (B=5, N=20, T=20, fill=0.5, r=2) ---\n")
  smoke_nnr <- run_ols_vs_nnr(N = 20L, TT = 20L, r = 2L, beta = 1.0,
                               B = 5L, nc = 1L)
  print(smoke_nnr)
}
